### ISSUE TITLE
Suggestion: change ES6 classes font color.

### ISSUE THREAD

**Issue by gonzamvita** [wesbos/cobalt2#103]
Hello,

When you declare a new ES6 class the 'class' keyword and the name of the class have both the same text color (see image). It will be cool to change class name to another color (maybe red? :p).

http://i.imgur.com/4iZO4CJ.jpg

Regards!

**Comment by wesbos** [comment]
![](http://wes.io/gIvh/content)

**Comment by wesbos** [comment]
I also updated the color of the object keys because they were the same colour as strings

**Comment by wesbos** [comment]
done done done - your sublime will update within a few hours

**Comment by gonzamvita** [comment]
Thanks _Boss_ 👍

**Comment by gonzamvita** [comment]
Hmmmmm, I don't know why, but I still see the same colors :(

**Comment by zeewebdev** [comment]
Hi, Wes. I see same color in function Expression
 var getPrice = function(){
			return 5.99;
}
both var and getPrice is displaying yellow color

**Comment by nMustaki** [comment]
Same issue here as zeewebdev, maybe a priority issue as getPrice is both a function and a variable in this case ?
By the way, what's the font you're using for the screenshots ?
Thanks for Cobalt, it's really great !

**Comment by jcberquist** [comment]
@wesbos: FYI, in the default JavaScript syntax, class names will have the scope `entity.name.class.js` in the next dev build (they currently have `entity.name.type.class.js`). 

Also, in that syntax, unquoted object keys do not get the scope `string.unquoted.label.js` any more. All object keys do get the scope `meta.object-literal.key.js` so if you want to target unquoted object keys in the default JavaScript syntax you could use `meta.object-literal.key.js -string`.

**Comment by wesbos** [comment]
Ah, good to know! confusing stuff - mind submitting a PR?
