### ISSUE TITLE
new vscode theme - search highlight

### ISSUE THREAD

**Issue by codeofsumit** [wesbos/cobalt2#155]
![image](https://user-images.githubusercontent.com/2399810/30349124-1f3b7628-9812-11e7-8259-47672c4433a5.png)

seems a bit too bright ;)

**Comment by codeofsumit** [comment]
fixed in the current release
![image](https://user-images.githubusercontent.com/2399810/30396775-027788e2-98cb-11e7-98b6-3342460a043c.png)

**Comment by codeofsumit** [comment]
I still see issues though. Let's say you searched a term and then doubleclick it (highlight), you barely see it marked
![image](https://user-images.githubusercontent.com/2399810/30397187-4f651d9e-98cc-11e7-90b6-7ef91845156a.png)

**Comment by wesbos** [comment]
Yeah I still don't know how to style this - I have an open issue for it. I'd recommend using the CSS addons I've put in the readme:

![](http://wes.io/mTLE/content)
